
export interface UserStats {
  steps: number;
  calories: number;
  sleep: number; // hours
  heartRate: number;
  water: number; // ml
}

export interface Message {
  role: 'user' | 'assistant';
  content: string;
}

export enum ViewType {
  DASHBOARD = 'DASHBOARD',
  MASTERS = 'MASTERS',
  COMPANIES = 'COMPANIES',
  PROJECTS = 'PROJECTS',
  SUBPROJECT = 'SUBPROJECT',
  UNITS = 'UNITS',
  WAREHOUSES = 'WAREHOUSES',
  LABOURS = 'LABOURS',
  ASSETS_EQUIPMENTS = 'ASSETS_EQUIPMENTS',
  VENDORS = 'VENDORS',
  ACTIVITIES = 'ACTIVITIES',
  MATERIALS = 'MATERIALS',
  COMPANY_USERS = 'COMPANY_USERS',
  MANAGE_TEAMS = 'MANAGE_TEAMS',
  USER_ROLES_PERMISSIONS = 'USER_ROLES_PERMISSIONS',
  PROJECT_PERMISSIONS = 'PROJECT_PERMISSIONS',
  PR_MANAGEMENT = 'PR_MANAGEMENT',
  PR_APPROVAL_MANAGE = 'PR_APPROVAL_MANAGE',
  PR = 'PR',
  REPORTS = 'REPORTS',
  WORK_PROGRESS_REPORTS = 'WORK_PROGRESS_REPORTS',
  INVENTORY_REPORTS = 'INVENTORY_REPORTS',
  LABOUR_STRENGTH = 'LABOUR_STRENGTH',
  WORK_CONTRACTOR = 'WORK_CONTRACTOR',
  SUBSCRIPTION = 'SUBSCRIPTION',
  LABOUR_MANAGEMENT = 'LABOUR_MANAGEMENT',
  AI_COACH = 'AI_COACH'
}

export type ThemeType = 'dark' | 'light';
