
export interface UserStats {
  steps: number;
  calories: number;
  sleep: number; // hours
  heartRate: number;
  water: number; // ml
}

export interface Message {
  role: 'user' | 'assistant';
  content: string;
}

export enum ViewType {
  DASHBOARD = 'DASHBOARD',
  MASTERS = 'MASTERS',
  COMPANIES = 'COMPANIES',
  PROJECTS = 'PROJECTS',
  SUBPROJECT = 'SUBPROJECT',
  UNITS = 'UNITS',
  WAREHOUSES = 'WAREHOUSES',
  LABOURS = 'LABOURS',
  ASSETS_EQUIPMENTS = 'ASSETS_EQUIPMENTS',
  VENDORS = 'VENDORS',
  ACTIVITIES = 'ACTIVITIES',
  MATERIALS = 'MATERIALS',
  COMPANY_USERS = 'COMPANY_USERS',
  MANAGE_TEAMS = 'MANAGE_TEAMS',
  USER_ROLES_PERMISSIONS = 'USER_ROLES_PERMISSIONS',
  PROJECT_PERMISSIONS = 'PROJECT_PERMISSIONS',
  PR_MANAGEMENT = 'PR_MANAGEMENT',
  PR_APPROVAL_MANAGE = 'PR_APPROVAL_MANAGE',
  PR = 'PR',
  REPORTS = 'REPORTS',
  WORK_PROGRESS_REPORTS = 'WORK_PROGRESS_REPORTS',
  WORK_PROGRESS_DETAILS = 'WORK_PROGRESS_DETAILS',
  DPR = 'DPR',
  RESOURCES_USAGE_FROM_DPR = 'RESOURCES_USAGE_FROM_DPR',
  MATERIAL_USED_VS_STORE_ISSUE = 'MATERIAL_USED_VS_STORE_ISSUE',
  INVENTORY_REPORTS = 'INVENTORY_REPORTS',
  INVENTORY_PR = 'INVENTORY_PR',
  INVENTORY_RFQ = 'INVENTORY_RFQ',
  INVENTORY_GRN_MRN_SLIP = 'INVENTORY_GRN_MRN_SLIP',
  INVENTORY_GRN_MRN_DETAILS = 'INVENTORY_GRN_MRN_DETAILS',
  INVENTORY_ISSUE_SLIP = 'INVENTORY_ISSUE_SLIP',
  INVENTORY_ISSUE_OUTWARD_DETAILS = 'INVENTORY_ISSUE_OUTWARD_DETAILS',
  INVENTORY_ISSUE_RETURN = 'INVENTORY_ISSUE_RETURN',
  INVENTORY_GLOBAL_STOCK_DETAILS = 'INVENTORY_GLOBAL_STOCK_DETAILS',
  INVENTORY_PROJECT_STOCK_STATEMENT = 'INVENTORY_PROJECT_STOCK_STATEMENT',
  LABOUR_STRENGTH = 'LABOUR_STRENGTH',
  WORK_CONTRACTOR = 'WORK_CONTRACTOR',
  SUBSCRIPTION = 'SUBSCRIPTION',
  LABOUR_MANAGEMENT = 'LABOUR_MANAGEMENT',
  DOCUMENT_MANAGEMENT = 'DOCUMENT_MANAGEMENT',
  AI_AGENTS = 'AI_AGENTS',
  AI_COACH = 'AI_COACH'
}

export type ThemeType = 'dark' | 'light';
